apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        upstream flask_app {
            server devops-BP-service:80;
        }

        server {
            listen 80;

            location / {
                proxy_pass http://flask_app;
            }
        }
    }